// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"database/sql"
	"time"
)

type Pullrequest struct {
	ID           int64        `json:"id"`
	Number       int64        `json:"number"`
	Action       string       `json:"action"`
	RepositoryID int64        `json:"repository_id"`
	Status       string       `json:"status"`
	Url          string       `json:"url"`
	Title        string       `json:"title"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ClosedAt     sql.NullTime `json:"closed_at"`
	Additions    int32        `json:"additions"`
	Deletions    int32        `json:"deletions"`
	ChangedFiles int32        `json:"changed_files"`
	Commits      int32        `json:"commits"`
}

type Repository struct {
	ID         int64     `json:"id"`
	Repository string    `json:"repository"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	IsAdmin   bool           `json:"is_admin"`
	GitName   sql.NullString `json:"git_name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
