// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: pullrequest.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const checkPullRequestExists = `-- name: CheckPullRequestExists :one
select count(*) from pullrequest where number = $1 and repository_id = $2
`

type CheckPullRequestExistsParams struct {
	Number       int64 `json:"number"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) CheckPullRequestExists(ctx context.Context, arg CheckPullRequestExistsParams) (int64, error) {
	row := q.queryRow(ctx, q.checkPullRequestExistsStmt, checkPullRequestExists, arg.Number, arg.RepositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPullRequest = `-- name: CreatePullRequest :exec
insert into pullrequest (number, action, repository_id, status, url, title, created_at, updated_at, closed_at, additions, deletions, changed_files, commits)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreatePullRequestParams struct {
	Number       int64        `json:"number"`
	Action       string       `json:"action"`
	RepositoryID int64        `json:"repository_id"`
	Status       string       `json:"status"`
	Url          string       `json:"url"`
	Title        string       `json:"title"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ClosedAt     sql.NullTime `json:"closed_at"`
	Additions    int32        `json:"additions"`
	Deletions    int32        `json:"deletions"`
	ChangedFiles int32        `json:"changed_files"`
	Commits      int32        `json:"commits"`
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error {
	_, err := q.exec(ctx, q.createPullRequestStmt, createPullRequest,
		arg.Number,
		arg.Action,
		arg.RepositoryID,
		arg.Status,
		arg.Url,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.Additions,
		arg.Deletions,
		arg.ChangedFiles,
		arg.Commits,
	)
	return err
}

const getPullRequest = `-- name: GetPullRequest :one
select id, number, action, repository_id, status, url, title, created_at, updated_at, closed_at, additions, deletions, changed_files, commits from pullrequest where id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, id int64) (Pullrequest, error) {
	row := q.queryRow(ctx, q.getPullRequestStmt, getPullRequest, id)
	var i Pullrequest
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Action,
		&i.RepositoryID,
		&i.Status,
		&i.Url,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.Commits,
	)
	return i, err
}

const updatePullRequest = `-- name: UpdatePullRequest :exec
update pullrequest set action = $1, status = $2, url = $3, title = $4, updated_at = $5, closed_at = $6, additions = $7, deletions = $8, changed_files = $9, commits = $10
where number = $11 and repository_id = $12
`

type UpdatePullRequestParams struct {
	Action       string       `json:"action"`
	Status       string       `json:"status"`
	Url          string       `json:"url"`
	Title        string       `json:"title"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ClosedAt     sql.NullTime `json:"closed_at"`
	Additions    int32        `json:"additions"`
	Deletions    int32        `json:"deletions"`
	ChangedFiles int32        `json:"changed_files"`
	Commits      int32        `json:"commits"`
	Number       int64        `json:"number"`
	RepositoryID int64        `json:"repository_id"`
}

func (q *Queries) UpdatePullRequest(ctx context.Context, arg UpdatePullRequestParams) error {
	_, err := q.exec(ctx, q.updatePullRequestStmt, updatePullRequest,
		arg.Action,
		arg.Status,
		arg.Url,
		arg.Title,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.Additions,
		arg.Deletions,
		arg.ChangedFiles,
		arg.Commits,
		arg.Number,
		arg.RepositoryID,
	)
	return err
}
