// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"context"
)

type Querier interface {
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (GroupUser, error)
	CheckGroupExists(ctx context.Context, id int64) (int64, error)
	CheckPullRequestExists(ctx context.Context, arg CheckPullRequestExistsParams) (int64, error)
	CheckRepositoryExists(ctx context.Context, repository string) (int64, error)
	CheckUserByEmail(ctx context.Context, email string) (int64, error)
	CheckUserByID(ctx context.Context, id int64) (int64, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error
	CreatePullRequestRole(ctx context.Context, arg CreatePullRequestRoleParams) (PullrequestRole, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGroup(ctx context.Context, id int64) error
	DeletePullRequestRole(ctx context.Context, id int64) error
	DeleteRepository(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroups(ctx context.Context) ([]Group, error)
	GetPullRequest(ctx context.Context, id int64) (Pullrequest, error)
	GetPullRequestRole(ctx context.Context, id int64) (PullrequestRole, error)
	GetPullRequestRoles(ctx context.Context, repositoryID int64) ([]PullrequestRole, error)
	GetRepositories(ctx context.Context) ([]Repository, error)
	GetRepositoryByID(ctx context.Context, id int64) (Repository, error)
	GetRepositoryByRepository(ctx context.Context, repository string) (Repository, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetUsersByGroup(ctx context.Context, groupID int64) ([]User, error)
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdatePullRequest(ctx context.Context, arg UpdatePullRequestParams) error
	UpdatePullRequestRole(ctx context.Context, arg UpdatePullRequestRoleParams) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
