// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"context"
)

type Querier interface {
	CheckPullRequestExists(ctx context.Context, arg CheckPullRequestExistsParams) (int64, error)
	CheckRepositoryExists(ctx context.Context, repository string) (int64, error)
	CheckUserByEmail(ctx context.Context, email string) (int64, error)
	CheckUserByID(ctx context.Context, id int64) (int64, error)
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteRepository(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetPullRequest(ctx context.Context, id int64) (Pullrequest, error)
	GetRepositories(ctx context.Context) ([]Repository, error)
	GetRepositoryByID(ctx context.Context, id int64) (Repository, error)
	GetRepositoryByRepository(ctx context.Context, repository string) (Repository, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdatePullRequest(ctx context.Context, arg UpdatePullRequestParams) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
