FROM golang:1.20 AS base

ENV GO111MODULE="on"
ENV GOOS="linux"
ENV CGO_ENABLED=1

# System dependencies
RUN curl -L https://downloads.sqlc.dev/sqlc_1.19.1_linux_amd64.tar.gz| tar xvz && mv sqlc /usr/local/bin
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz && mv migrate /usr/local/bin
RUN go install gotest.tools/gotestsum@latest
RUN go install github.com/golang/mock/mockgen@v1.6.0
RUN go install github.com/smartystreets/goconvey@latest

ARG PROJECT_NAME="app"
ARG VERSION="dev"
ARG COMMIT="none"
ENV CGO_ENABLED=0
ENV GOPROXY=https://proxy.golang.org

FROM base AS dev
WORKDIR /app

COPY . .

RUN go mod download
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Hot reloading mod
RUN go get -u github.com/cosmtrek/air && go install github.com/go-delve/delve/cmd/dlv@latest

RUN go install github.com/cosmtrek/air@latest

EXPOSE 8080
EXPOSE 2345

ENTRYPOINT ["/go/bin/air"]
